[application]
name = "yaydlp"

[bundle]
identifier = "com.bilal.yaydlp"
publisher = "Bilal"
short_description = "A desktop downloader for yt-dlp workflows"

[web.app]

title = "yaydlp"

[web.resource]

style = []

script = []

[web.resource.dev]

script = []
